api_token_env: CROWDIN_API_TOKEN
project_id_env: CROWDIN_PROJECT_ID
preserve_hierarchy: true
files:
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
